---
title: "macroinvertebrate_processing_2021_in-house-processed"
author: 'NYSDEC SMAS : Keleigh Reynolds'
date: "2/3/2021"
output: html_document
params:
  file_name: "L:/DOW/BWAM Share/data/lab_data/WAA/2024/raw/Copy-DeerRiver_MacroTaxa.csv"
  user: kareynol
  file_type: "waa"
---

```{r include=FALSE,message=FALSE}
library(dplyr)

#file_type options : "waa" or "internal"

#run the functions script
source("functions.R")

```

```{r}
#first read in the raw file
#raw<-readxl::read_excel("C:/Users/kareynol/Desktop/R_SMAS/macro_processing_in_house/data/SampData_2018.xlsx")

raw<-read.csv(params$file_name)

#check date format on the input data
IsDate <- function(mydate, date.format = "%d/%m/%Y") {
x<-tryCatch(!is.na(as.Date(mydate, date.format)))
if("FALSE" %in% x){
   return("The dates are not in the right format, please re-format to %d/%m/%Y")
}
}

IsDate(raw$MSSIH_EVENT_SMAS_SAMPLE_DATE)

#fix the dates for the 2024 data files
raw<-raw %>% 
  mutate(MSSIH_EVENT_SMAS_SAMPLE_DATE = format(as.Date(MSSIH_EVENT_SMAS_SAMPLE_DATE,"%d-%m-%Y"),"%d/%m/%Y"),
         group = "")

#raw<-read.csv("C:/Users/kareynol/OneDrive - New York State Office of Information Technology Services/Desktop/raw/Copy of USGS_540_13_MacroTaxaOutput.csv") #for scott george

#12/6/2022 merge all the new files to get the table correct
# raw2<-read.csv(here::here("data/MacroData_2021_kar.csv"))
# raw3<-read.csv(here::here("data/Esopus_MacroData_2021.csv"))
# raw3$X._Grids<-""
# raw_all<-rbind(raw,raw2,raw3)
#raw<-raw_all

#raw<-read.csv("L:/DOW/BWAM Share/data/lab_data/WAA/2023/raw/Copy of MacroTaxa_470.23-078_085.csv")

if(params$file_type=="internal"){m_data_prep(raw)}

if(params$file_type=="waa"){waa_data_prep(raw)
 prepped_df<-prepped_df3 #renames and copies the df that was made 
}



```

## Run the species QA script to see if any are not matching the Master table.

```{r}
#check to see if there is a file called "newly_found_species.csv" in the outputsfolder. If there is, please rename it 
site_check(prepped_df)

species_check(prepped_df)

#for 2022 data
# prepped_df<-prepped_df %>%
#   mutate(MSDH_GENSPECIES=case_when(
#     MSDH_GENSPECIES == "neoleptophlebia_sp."~"undetermined_leptophlebiidae",
#     TRUE~MSDH_GENSPECIES))
# 
# #for 2022 lakes data - 10/24/2023
# 
# prepped_df<-prepped_df3 %>% 
#   #subset(site_id != "HWF") %>% 
#   subset(site_id == "04-LHONYE-1.0") %>% 
#   subset(site_id == "04-LHONYE-0.0")



```

```{r}
#prep for tables for Data Mod: this will do the macro species sample event table and the 
#Sample info history tables, and save it to the outputs folder with today's date.

if (params$file_type=="internal"){tables_1_2(prepped_df)}
if (params$file_type=="waa"){tables_1_2.waa(prepped_df)}

```

```{r function for event corrections}

correct_site_name <- function(df, vars) {
  final_df <- df |>
    dplyr::mutate(
      dplyr::across(
        {{vars}},
        site_corrections
      ),
      .before = everything()
    )
}

site_corrections <- function(col) {
  stringr::str_replace_all(
    col,
    c("12-SAUQ-2.2" = "12-SAUQ-1.7",
      "13-LHUD-105" = "13-LHUD-105.0",
      "14-LBEV-0.1" = "14-LBEV_T03-0.1",
      "14-LBEV-0.4" = "14-LBEV_T01-0.4",
      "14-LBEV-0.3" = "14-LBEV_T04-0.3",
      "11-TWNS-0.2" = "11-STEB-0.2",
      "11-TWNS-1.1" = "11-STEB-1.1",
      "06-BIBS-0.3" = "06-JENC-0.3",
      "06-BIBS-6.6" = "06-JENC-6.6",
      "12-BATV-11.5" = "12-MITB-0.1",
      "13-BVRD-0.8" = "13-SHIR-0.8",
      "13-BVRD-1.0" = "13-SHIR-1.0",
      "13-BVRD-2.8" = "13-SHIR-2.8",
      "13-BVRD-4.8" = "13-SHIR-4.8",
      "05-CAMP- 1.5" = "05-CAMB-1.5",
      "06-FABS-5.0" = "06-TOLF-1.8",
      "12-SCHE-0.6" = "12-BRWC-0.6",
      "12-SCHE-0.8" = "12-COWC-0.8",
      "05-SEEL-0.5" = "05-MLIC-0.5",
      "11-SNOK-0.3" = "11-SNOK_L-0.3",
      "13-TACK-0.1" = "13-SPAR_T10-0.1",
      "06-CATH_T9_3a-0.5" = "05-CATH_T9_3a-0.5",
      "07-SKAT_1-0.2" = "07-SKAT_T89-0.2",
      "07-CAYG_2-1.1" = "07-CAYG-1.1",
      "07-BSWP_1.3" = "07-BSWP-1.3",
      "13-LINK-2.3" = "15-LINK-2.3",
      "07-GROU_1-1.5" = "07-GROU-1.5",
      "04-BAKE-0.3" = "04-BKER-0.3",
      "07-BLKC-2.8" = "11-BLKC-2.8",
      "07-BLCK-2.8" = "11-BLKC-2.8",
      "07-BUTN-0.6" = "07-BTNC-0.6",
      "14-COLE-0.4" = "14-CCLV-0.4",
      "05-CRAN-0.1" = "05-CRBP-0.1",
      "07-DEAN-1.9" = "07-DNCR-1.9",
      "07-FISC-1.3" = "07-FSHR-1.3",
      "10-JACK-0.2" = "10-JKBR-0.2",
      "08-LIME-6.7" = "08-LMKN-6.7",
      "13-SILV-4.5" = "13-SILS-4.5",
      "04-COHO_T41-0.1" = "05-COHO_T41-0.1",
      "07-SPRN_T7-0.1" = "04-SPRN_T7-0.1",
      "07-SENP_T32-0.6" = "04-SENP_T32-0.6",
      "07-MUDG_T72-0.3" = "04-MUDG_T72-0.3",
      "12-DWAS-7.2" = "11-DWAS-7.2",
      "04-GRIM-6.3" = "07-GRIM-6.3",
      "02-JNSN-2.3" = "03-JNSN-2.3",
      "02-MUDC-0.4" = "03-MUDC-0.4",
      "04-TNCR-3.7" = "05-TNCR-3.7",
      "03-WCAN-73.0" = "04-WCAN-73.0",
      "95-COHO-28.6" = "05-COHO-28.6",
      "04-SXML-2.2" = "07-SXML-2.2",
      "12-HVLY-0.5" = "12-HLVY-0.5",
      "11-UHUD-42.5" = "11-UHUD-43.1",
      "12-MOHK-3.7" = "12-MOHK-1.5",
      "05-CHAU-14.9" = "01-CHAU-14.9",
      "05-TOGA-1.5" = "05-TOGA-1.3",
      "13-SPAR_T96-01" = "13-SPAR_T9b-0.1",
      "13-TINW-4.55" = "13-TINW-4.5",
      "13TINW-4.5" = "13-TINW-4.5",
      "13TINW-6.5" = "13-TINW-6.5",
      "15-DEFT_T1-0.5" = "15-DEFT_T1-0.1",
      "15-DEFT_T1-0.2" = "15-DEFT_T1-0.1",
      "13-STNY-8.1" = "13-STNY-10.0",
      "14-GOUL-0.9" = "14-COUL-0.9",
      "12-NORT-1.7" = "12-NORT-2.3",
      "05-CHAU-4.2" = "05-CHAU-4.0",
      "02-CLER_T6-3.1" = "02-TWTY-3.1",
      "12-STLE-0.8" = "12-STLE-0.2",
      "13-BRNX-5.6" = "17-BRNX-5.6",
      "11-LRNC_21-20.2" = "11-UHUD-64.4",
      "11-UHUD-14.7" = "11-UHUD-14.8",
      "11-UHUD-27.5" = "11-UHUD-27.4",
      "11-UHUD-32.1" = "11-UHUD-32.4",
      "11-UHUD-39.5" = "11-UHUD-40.1",
      "11-UHUD-39.8" = "11-UHUD-40.3",
      "11-UHUD-42.5" = "11-UHUD-43.1",
      "11-UHUD-51.0" = "11-UHUD-51.3",
      "11-UHUD-64.0" = "11-UHUD-64.2",
      "11-UHUD-98.3" = "11-UHUD-98.7",
      "11-UHUD-267.8" = "11-UHUD-106.3",
      "11-UHUD-273.0" = "11-UHUD-111.6",
      "11-UHUD-284.9" = "11-UHUD-124.2",
      "11-UHUD-286.0" = "11-UHUD-124.7",
      "11-XHR-273.0" = "11-UHUD-111.6",
      "11-XHR-277.0" = "11-UHUD-115.6",
      "11-XHR-282.3" = "11-UHUD-120.9",
      "11-XHR-285.0" = "11-UHUD-124.3",
      "11-XHR-286.6" = "11-UHUD-125.3",
      "13-LHUD-25.8" = "13-LHUD-5.7",
      "13-LHUD-35.0" = "13-LHUD-14.7",
      "13-LHUD-39.7" = "13-LHUD-19.5",
      "13-LHUD-50.3" = "13-LHUD-47.5",
      "13-LHUD-50.59" = "13-LHUD-47.8",
      "13-LHUD-50.6" = "13-LHUD-47.9",
      "13-LHUD-50.61" = "13-LHUD-47.9",
      "13-LHUD-66.3" = "13-LHUD-63.6",
      "13-LHUD-67.3" = "13-LHUD-64.6",
      "13-LHUD-89.3" = "13-LHUD-88.7",
      "13-LHUD-104.6" = "13-LHUD-105",
      "13-LHUD-119.6" = "13-LHUD-124.9",
      "13-LHUD-120.2" = "13-LHUD-125.5",
      "13-LHUD-124.1" = "13-LHUD-128.9",
      "13-LHUD-125.8" = "13-LHUD-130.6",
      "13-LHUD-133.4" = "13-LHUD-140.1",
      "13-LRNC_22-89.3" = "13-LHUD-88.6",
      "13-LRNC_63-133.4" = "13-LHUD-140.1",
      "13-LRNC_66-119.6" = "13-LHUD-124.9",
      "03-YANT_T1C-0.2" = "03-YANT_T1c-0.2",
      "17-GSCK_TA-0.1" = "17-GSCK_Ta-0.1",
      "07-SKAT_T93A-0.5" = "07-SKAT_T93a-0.5",
      "06-SANG_TB-0.1" = "06-SANG_Tb-0.1",
      "05-CATH_T9_3A-0.5" = "05-CATH_T9_3a-0.5",
      "07-SKAT_T93A-0.5" = "07-SKAT_T93a-0.5",
      "14-CALL_E_T13A-0.1" = "14-CALL_E_T13a-0.1",
      "09-STLW_T46A-0.1" = "09-STLW_T46a-0.1",
      "07-SKAT_T93A-0.5" = "07-SKAT_T93a-0.5",
      "12-SCHO_T93_B-1.8" = "12-SCHO_T93_b-1.8",
      "13-SPAR_T9B-0.1" = "13-SPAR_T9b-0.1",
      "17-BLND_TB-2.0" = "17-BLND_Tb-2.0",
      "17-KENF_TA-0.2" = "17-KENF_Ta-0.2",
      "07-KDIG_TB-0.7" =  "07-KDIG_Tb-0.7",
      "17-KENF_TA-0.2" = "17-KENF_Ta-0.2",
      "17-BLND_TB-2.0" = "17-BLND_Tb-2.0",
      "17-KENF_TA-0.2" = "17-KENF_Ta-0.2",
      "17-BLND_TB-2.0" = "17-BLND_Tb-2.0",
      "13-SPAR_T9B-0.1" = "13-SPAR_T9b-0.1",
      "02-WRGT_TA-1.8" = "02-WRGT_Ta-1.8",
      "13-LHUD-47.91" = "13-LHUD-47.9",
      "05-MILD_T7-0.3" = "04-MILD_T7-0.3",
      "12-SMIB-0.5"= "10-SMIB-0.5"
      # "11-UHUD-43.1",
      # "13-PATS-0.5",
      # "13-PATS-1.3",
      # "13-PATS-1.8",
      # "12-SAUQ-1.7",
      # "12-POEN-2.0",
    )
  )
}

macro_event_corrections <- function(df) {
  mutate(
    df,
    event_id = case_match(
      event_id,
      "12-MOYR-5.1_20100729" ~ "12-MOYR-5.1_20100728",
      "12-OTSO -1.1_20200714" ~ "12-OTSO-1.1_20200714",
      "01-LBUF-2.5_20200917" ~ "01-LBUF-2.5_20200915",
      "02-WFREN_T12-0.2_20210915" ~ "02-WFREN_T12-0.5_20210915",
      "1-BUFF-1.7_20200902" ~ "1-BUFF-1.7_20200901",
      "01-BUFF-1.7_20200902" ~ "01-BUFF-1.7_20200901",
      "11-WBLA-0.9_20210803" ~ "11-WBLA-0.9_20210805",
      "04-UGNS-139.6_20220929" ~ "04-UGNS-139.6_20220921",
      "05-COHO_T1-0.1_20220830" ~ "05-COHO_T1-0.1_20220831",
      "05-FIVM-13.0_20220830" ~ "05-FIVM-13.0_20220831",
      "05-STEO_T22-0.2_20220830" ~ "05-STEO_T22-0.2_20220831",
      "06-SUSQ-36.9_20220713" ~ "06-SUSQ-36.9_20220712",
      "08-FALK-0.3_20220914" ~ "08-FALK-0.3_20220915",
      "08-MILE-0.7_20220914" ~ "08-MILE-0.7_20220915",
      "08-TANE-0.7_20220913" ~ "08-TANE-0.7_20220914",
      "13-SPAR-3.6_20220714" ~ "13-SPAR-3.6_20220719",
      "12-SPIT-2.3_20210723" ~ "12-SPIT-2.3_20200723",
      "12-WESK-0.1_20200716" ~ "12-WESK_T5-0.1_20200716",
      "07-CANO-2.3_20210721" ~ "07-CANO-0.8_20210721",
      "07-DEAN-0.1_20210721" ~ "07-DEAN-1.9_20210721",
      "13-ESOP-4.4_20220720" ~ "13-ESOP-4.8_20220720",
      # "13-POST-0.8_20220719" ~ "13-POST-18.4_20220719",
      # "13-ROND-9.2_20220719" ~ "13-ROND-32.2_20220719",
      "13-TIOR-0.2_20220720" ~ "13-TIOR-0.1_20220720",
      "07-FISC-0.1_20210722" ~ "07-FISC-1.3_20210722",
      "07-POTT-0.7_20210831" ~ "07-POTT-0.1_20210831",
      "07-RHCR-0.8_20210713" ~ "07-RHCR-0.7_20210713",
      "07-RHCR-0.8_20210901" ~ "07-RHCR-0.7_20210901",
      "11-UHUD-125.3_20210803" ~ "11-UHUD-124.7_20210803",
      "01-CHAU-4.2_20220922" ~ "01-CHAU-4.0_20220922",
      "05-CDEA-11.4_20220831" ~ "05-CDEA-11.5_20220831",
      "05-CHEM-33.8_20220830" ~ "05-CHEM-33.6_20220830",
      "05-COHO-1.4_20220830" ~ "05-COHO-1.5_20220830",
      "05-PURD-0.1_20220831" ~ "05-PURD-0.2_20220831",
      # "05-TRPS-9.5_20220901" ~ "05-TRPS-7.0_20220901",
      "08-BLCK-30.0_20220802" ~ "08-BLCK-30.4_20220802",
      "08-LIME-6.3_20220914" ~ "08-LIME-6.7_20220914",
      "08-WHET-4.8_20220914" ~ "08-WHET-4.9_20220914",
      "11-XHR-296.0_20210803" ~ "11-UHUD-296.7_20210803",
      "05-MDCR-10.0_20220821" ~ "05-MDCR-10.0_20220831",
      "05-MEAD-10.8_20220831" ~ "05-MEAD-10.9_20220830",
      "07-VENS-1.8_20210722" ~ "07-VENE-1.5_20210722",
      "03-LSTN-1.0_20200801" ~ "03-LSTN-1.0_20200819",
      "08-ADKS_36-0.5_20220914" ~ "08-ADKS_36-0.6_20220914",
      "08-BLCK_T132-2.0_20220915" ~ "08-BLCK_T132-1.8_20220915",
      "09-BRND-2.5_20210728" ~ "09-BRND-1.6_20210728",
      "09-COLE-2.9_20210727" ~ "09-COLE-3.6_20210727",
      "09-COLE-4.6_20210727" ~ "09-COLE-4.2_20210727",
      "12-FOX-1.1_20220809" ~ "12-FOX-1.1_20220810",
      "13-LHUD_T299-2.5_20220720" ~ "13-LHUD_T229-2.5_20220720",
      "13-WFKIL-0.1_20220721" ~ "13-WFKIL-0.4_20220721",
      "16-SUSQ-25.2_20220712" ~ "06-SUSQ-25.2_20220712",
      "10-JACK-0.2_20230726T1030" ~ "10-JKBR-0.2_20230726T1030",# fixing the site that doesn't match - same name as another waterbody 
      .default = event_id
    )
  ) 
}


```


```{r}
#Run BAP and create BAP entry for table
library(BAP)

#run BAP's data prep on the raw file
bap.prepped<-BAP::data_prep(prepped_df)
#2022 data fixes, references seemed odd
bap.prepped$REFERENCE<-""
bap.prepped<-bap.prepped %>% 
  distinct()



#split by collection method and run the appropriate BA
bap.final<-apply_bap(bap.prepped)

#this is probably where we can figure out the new code from - start here

#create metric file with correct names
metrics_final<-metric_table(bap.final)

write.csv(metrics.subset,here::here("outputs/deer_river_10_4_24_METRICS.csv"))

write.csv(metrics.subset,"L:/DOW/BWAM Share/data/lab_data/BAP_script_results/2024/deer_river_10_4.csv")

```

```{r}
## Taxonomy prep - added 12/23/2025

#Taxonomy prep

insect_dir <- file.path(
  "L:",
  "DOW",
  "BWAM Share",
  "data",
  "parquet",
  "build_tables",
  "TAXONOMY.parquet")

insect_name_dir <- file.path(
  "L:",
  "DOW",
  "BWAM Share",
  "data",
  "parquet",
  "build_tables",
  "PREVIOUS_TAXON_NAME.parquet")

insect_final_dir <- file.path(
  "L:",
  "DOW",
  "BWAM Share",
  "data",
  "parquet",
  "build_tables",
  "TAXONOMIC_ABUNDANCE.parquet")

insects_cw <- open_dataset(insect_dir) |> 
  filter() |> 
  # select(TAXON_ID) |> 
  distinct() |> 
  collect()

insects_cw_name <- open_dataset(insect_name_dir) |> 
  filter() |> 
  # select(TAXON_ID) |> 
  distinct() |> 
  collect()

taxa_obt<-open_dataset(insect_final_dir) |> 
  filter() |> 
  # select(TAXON_ID) |> 
  distinct() |> 
  collect()
#using Rhett's analysis to create the taxonomy obt fils
#adding project name
raw$Client_Project_Name <- "Deer River RAS"

raw<-raw |> 
  mutate(time = case_match(MSSIH_EVENT_SMAS_HISTORY_ID,
                          "09-DERR-16.9" ~ "1300",
                          "09-DERR-22.4" ~ "1130",
                          "09-DERR-18.2" ~ "1400",
                          "09-DERR-15.5" ~ "1230",
                          "09-DERR-17.6" ~ "845",
                          "09-DERR-17.4"  ~ "900",
                          .default = "12:00"),
         date_text = format(as.Date(MSSIH_EVENT_SMAS_SAMPLE_DATE,"%m/%d/%Y"),
                            format = "%Y%m%d"))

raw<-raw |> 
  mutate(event_id = paste(MSSIH_EVENT_SMAS_HISTORY_ID,"_",date_text,
                          "T",time,sep = ""))

# Renaming to DB standard -------------------------------------------------
taxa_raw <- raw |> #---------------- Renaming the preexisting columns that are given in the WAA report
  dplyr::select(SITE_CODEpre = MSSIH_EVENT_SMAS_HISTORY_ID,
                EVENT_DATETIME = MSSIH_EVENT_SMAS_SAMPLE_DATE,
                TAXON_ID = MSDH_GENSPECIES,
                RESULT_VALUE = MSDH_INDIVIDUAL_SPECIES_CNT,
                RESULT_COMMENT = MSSIH_TOTAL_INDIV_CNT_NOTE,
                SUBSAMPLE_AMOUNT = 'X._Grids',
                SAMPLE_METHOD = MSSIH_BIOSAMPLE_COLLECT_METHOD,
                event_id = event_id,
                REPLICATE = MSSIH_REPLICATE,
                LAB_SAMPLE_ID = "WAA.ID",
                PROJECT = Client_Project_Name)

#correct event ids
taxa_raw_event<-taxa_raw |> 
  macro_event_corrections() |> 
  mutate(site_id = site_corrections(SITE_CODEpre), 
         EVENT_DATETIME = as.Date(EVENT_DATETIME,
                                          format = "%m/%d/%Y")) #perfect! i think we wont need this anyway since we'll just hook it up with event_id


taxa_raw_event<-taxa_raw_event |> 
  mutate(SUBSAMPLE_AMOUNT_UNIT =
           ifelse(is.na(SUBSAMPLE_AMOUNT) | SUBSAMPLE_AMOUNT == "", "not_applicable", "grid"))
#this is assigning the SAMPLE_AMMOUNT_UNIT based on the value

#---------- Now all that is needed is to trim the fat, or pull only the data that is necessary 
taxa_final <- taxa_raw_event  |> 
  select(SITE_CODE = SITE_CODEpre, 
         "EVENT_DATETIME", 
         "TAXON_ID", 
         "RESULT_VALUE", 
         "SAMPLE_METHOD",
         "RESULT_COMMENT",
         "SUBSAMPLE_AMOUNT", 
         "SUBSAMPLE_AMOUNT_UNIT", 
         "REPLICATE", 
         "SAMPLE_METHOD", 
         EVENT_ID = event_id,
         "LAB_SAMPLE_ID",
         "PROJECT") |> 
  mutate(
    RESULT_QUALIFIER = "",
    UNIT = "count",
    SAMPLE_SOURCE = "lab",
    SAMPLE_TYPE = "macroinvertebrate_abundance"
  )

taxa_final2<- taxa_final %>%
  mutate(TAXON_ID = gsub("undetermined_", "", TAXON_ID),  
         TAXON_ID = gsub("_sp\\.|_gr\\.|_spp\\.", "", TAXON_ID),  # Remove all instances of _sp. and _gr.  
         TAXON_ID = gsub("undet\\._tubificidae_w/_cap\\._setae", "tubificidae_with_cap_setae", TAXON_ID),  # Replace specific string  
         TAXON_ID = gsub("undet\\._tubificidae_w/o_cap\\._setae", "tubificidae_without_cap_setae", TAXON_ID),  # Replace specific string  
         TAXON_ID = gsub("_complex", "_co", TAXON_ID),  
         TAXON_ID = gsub("_co", "_complex", TAXON_ID),  
         TAXON_ID = gsub("_complexlumella", "_columella", TAXON_ID),
         TAXON_ID = gsub("_complexrnutus", "_cornutus", TAXON_ID),
         TAXON_ID = gsub("_complexffmani", "_coffmani", TAXON_ID),
         TAXON_ID = gsub("/", "-", TAXON_ID),
         TAXON_ID = gsub("_nr\\.", "", TAXON_ID),
         TAXON_ID = gsub("\\?", "", TAXON_ID))

# checking against taxon CW -----------------------------------------------
cw_errors <- anti_join(taxa_final2, insects_cw, by = "TAXON_ID")

taxon_corrections <- function(col){
  stringr::str_replace_all(
    col,
    c("orthocladius_(euorthoclad.)_rivicola" = "orthocladius_euorthocladius_rivicola",
      "orthocladius_(symposiocladius)_lignicola" ="orthocladius-symposiocladius_lignicola",
      "drunella_complexrnutella"= "drunella_cornutella",
      "paraleptophlebia" = "leptophlebia",
      "lipiniella" = "chironomidae",
      "glossiphonia_complexmplanata" = "glossiphonia_complanata" ))}


taxa_final3<-taxa_final2 |> 
  mutate(TAXON_ID= taxon_corrections(TAXON_ID)) |> 
  #fix those - not sure why they wont do it in the code?
  mutate(TAXON_ID = case_when(TAXON_ID %in% "orthocladius_(euorthoclad.)_rivicola" ~ "orthocladius_euorthocladius_rivicola",
                                TAXON_ID %in% "orthocladius_(symposiocladius)_lignicola" ~ "orthocladius-symposiocladius_lignicola",
                                TRUE ~ TAXON_ID))

#check again
cw_errors <- anti_join(taxa_final3, insects_cw, by = "TAXON_ID")
#these look good!


taxa_final4<-taxa_final3 |> select("SITE_CODE", "EVENT_DATETIME", "TAXON_ID", 
"RESULT_VALUE", "SAMPLE_METHOD", "RESULT_COMMENT", "SUBSAMPLE_AMOUNT", 
"SUBSAMPLE_AMOUNT_UNIT", "REPLICATE", "SAMPLE_METHOD", "EVENT_ID",
"LAB_SAMPLE_ID", "PROJECT") |> 
  mutate(RESULT_QUALIFIER = 0,
         UNIT = "count",
         SAMPLE_SOURCE = "lab",
         SAMPLE_TYPE = "macroinvertebrate_abundance",
         LAB_ANALYTICAL_METHOD = "not_applicable",
         TEST_TYPE = "not_applicable",
         RESULT_CATEGORY = "not_applicable",
         LAB_QUALIFIER = "not_applicable",
         PREP_METHOD = "not_applicable",
         ANALYSIS_DATETIME = as.POSIXct(NA)
         
         )


#look if there are any missing columns

obt_cols<-names(taxa_obt)

missing<- setdiff(obt_cols,names(taxa_final4)) #just missing the obt assigned FKs

```

```{r validation}

# validation --------------------------------------------------------------

#look for dupes
# Find duplicate rows
duplicates <- taxa_final4 %>%
  group_by(across(c(EVENT_ID,REPLICATE,TAXON_ID))) %>%
  filter(n() > 1)  #duplicates in replicate for the RMN network - let's adjust these


#fix collection method
taxa_final4<-taxa_final4 |> 
   mutate(SAMPLE_METHOD = case_when(
    SAMPLE_METHOD %in% "Kick: Standard" ~ "kick_standard",
    SAMPLE_METHOD %in% "Multiplate: Navigable" ~ "multiplate_navigable",
    SAMPLE_METHOD %in% "Multiplate: Non-Navigable" ~ "multiplate_non-navigable",
    SAMPLE_METHOD %in% "Sediment Ponar" ~ "sediment_ponar",
    SAMPLE_METHOD %in% "Kick: Sandy Stream" ~ "kick_sandy-stream",
    SAMPLE_METHOD %in% "Kick: Headwater Stream" ~ "kick_standard",
    SAMPLE_METHOD %in% "Multihabitat: Lake" ~ "multihabitat_lake",
    SAMPLE_METHOD %in% "Low-Gradient" ~ "low_gradient",
    SAMPLE_METHOD %in% "Lake: Ponar" ~ "lake_ponar",
    SAMPLE_METHOD %in% "Lake: Littoral" ~ "lake_littoral",
    SAMPLE_METHOD %in% "Other: Various (Historical)" ~ "other_various-historical",
   TRUE ~ "unknown"))


saveRDS(
  object = taxa_final4,
  file = file.path(
    "L:",
    "DOW",
    "BWAM Share",
    "data",
    "data_warehouse_staging",
    "2025",
    "bap",
    "taxa_2024_deer_river.rds"
  )
)

```



